//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExWebAppSia.webpage
{
    public partial class WebForm3
    {
        protected global::System.Web.UI.WebControls.Repeater rptAttendance;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow noRecordsRow;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl attendanceTableBody;
    }
}
